### PR TITLE
feat: add heic image support

### PR DESCRIPTION
**Pull request by akseyh**
If applied, this pull request will add heic image support.
- Adds HEIC type
- Adds isHEIC validator
- Updates doc

### CODE REVIEW

**Review by nir11 — APPROVED** [review]

**Comment by nir11** [comment]
Awesome!
Thanks

**Comment by nir11** [comment]
I implemented a couple of fixes:
- Update HEIC signatures
- Change HEIC order in supported files list

**Comment by akseyh** [comment]
> 

Thanks. 
Cool repo, it worked for me a lot. Good job.

**Comment by nir11** [comment]
Thank you

**Pull request merged**
